### ISSUE TITLE
Enqueuing google font

### ISSUE THREAD

**Issue by sakinshrestha** [dsgreen/magnetic-wp#15]
* Enqueuing google font is a bit tricky. Also, WordPress.org might disallow google font linking. ( Keep track of this: https://make.wordpress.org/themes/2020/09/25/new-package-to-allow-locally-hosting-webfonts/ ). 
* To enqueue fonts, use this method: https://themeshaper.com/2014/08/13/how-to-add-google-fonts-to-wordpress-themes/

**Comment by dsgreen** [comment]
Closed by: https://github.com/dsgreen/magnetic-wp/pull/33
