### ISSUE TITLE
Theme name Magnetic WP

### ISSUE THREAD

**Issue by sakinshrestha** [dsgreen/magnetic-wp#16]
* Textdomain needs to be `magnetic-wp'`. I don't know if this is the final name for the theme or not. If Magnetic WP is the theme name, `theme-slug` needs to be `magnetic_wp` and textdomain needs to be `magnetic-wp`. Theme folder name also needs to be the same.

**Comment by dsgreen** [comment]
Hi Sakin, I added the "WP" after finding that "Magnetic" seems to have been taken on WP.org. However, it looks like that was an old unapproved theme. I've already resubmitted this theme under the Magnetic WP name. Are there any options for changing the name on an in-progress ticket, or would WP.org just consider a new name as a new theme?

**Comment by sakinshrestha** [comment]
Hi Doug, 

Yes, if Magnetic has already been used then "Magnetic WP" is a good name to.
* Textdomain and folder name should be `magnetic-wp`.
* Prefix needs to be `magnetic_wp`

**Comment by dsgreen** [comment]
Closed with: https://github.com/dsgreen/magnetic-wp/commit/2ad1faf0824bd096acb666610c4deb849eec942e
